#!/usr/bin/env sh

# Init activity archive if not already existing
if [ ! -f data/archives.json ]
then
  mkdir -p ./data
  echo '{}' > ./data/archives.json
fi

# Init activity archive if not already existing
if [ ! -f config/local.coffee ]
then
  ./node_modules/coffee-script/bin/coffee ./scripts/init_local_config.coffee
fi

# Init properties list if not already existing
if [ ! -f data/properties.json ]
then
  ./scripts/update_properties
fi
